import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import org.json.JSONObject;

/**
 * This class handles the reading of JSON files.
 * 
 * We scan through JSON data and parse it into a JSON object.
 * 
 * @author bluu8, jender
 */
public class JSONFileReader {
    JSONObject data = null; //Data field
    
    /**
     * The constructor builds a JSON object from a .json file, just iterating line-by-line
     * 
     * @param filename - The path of the JSON file. 
     * @throws FileNotFoundException if the file doesn't exist.
     */
    public JSONFileReader(String filename) throws FileNotFoundException {
        File file = new File(filename);
        Scanner scanner = new Scanner(file);
        
        String strdata = "";
        
        while (scanner.hasNextLine()) strdata += scanner.nextLine(); //Fetch the text line by line
        data = new JSONObject(strdata); //New JSON object
        scanner.close();
    }
    
    /**
     * This method returns the JSON object generated by the previous code.
     * 
     * @return The data in the JSON object 
     */
    public JSONObject getData() {
        return data;
    }
}
