
import java.io.File;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 * This class implements POI editing, using javax.swing for the GUI.
 * 
 * 
 * The constructor generates the form you can see on the Swing page, and the rest of the code is devoted
 * to event listeners for each user action.
 * 
 * @author bluu8, jender
 */
public class POIEditor extends javax.swing.JFrame {

    // the POI we are editing
    POI currentPOI = null;
    boolean confirmDelete = false;
    
    /**
     * The constructor for this method takes the POI data and generates the Swing form based on it.
     * 
     * We grab all of the POI data create a user-friendly Swing form so that the 
     * POI information can be edited.
     * 
     * @param poi - The POI we're editing.
     */
    public POIEditor(POI poi) {
        initComponents();
        currentPOI = poi;
        
        if (currentPOI.getName() != null) {
            this.setTitle("Edit POI: " + poi.getName());
            poiNameField.setText(poi.getName());
            poiCategoryField.setText(poi.getCategory());
            poiIconField.setText(poi.getIcon());
            poiDescriptionField.setText(poi.getDescription());
            createPOIButton.setText("Edit POI");
            headingLabel.setText("Edit POI");
            deletePOIButton.setText("Delete POI");
            deletePOIButton.setForeground(java.awt.Color.RED);
        }
        else {
            this.setTitle("Create POI");
        }
        
        poiCoordinateLabel.setText("Coordinates Selected: (" + poi.getX() + ", " + poi.getY() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        poiNameField = new javax.swing.JTextField();
        poiCategoryField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        createPOIButton = new javax.swing.JButton();
        deletePOIButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        poiIconField = new javax.swing.JTextField();
        poiDescriptionField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        poiCoordinateLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headingLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        headingLabel.setText("Create POI");

        jLabel2.setText("Name");

        jLabel3.setText("Category");

        createPOIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPOIButton.setText("Create POI");
        createPOIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPOIButtonActionPerformed(evt);
            }
        });

        deletePOIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletePOIButton.setText("Cancel");
        deletePOIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePOIButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Icon");

        poiIconField.setText("default");

        poiDescriptionField.setText("I am a brief description");

        jLabel7.setText("Description");

        poiCoordinateLabel.setText("Coordinates Selected: (0, 0)");

        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText(" ");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Leave icon field blank for default");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/pencil.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poiIconField)
                            .addComponent(poiNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poiCategoryField)
                            .addComponent(poiDescriptionField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poiCoordinateLabel)
                            .addComponent(errorLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(headingLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(createPOIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletePOIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(poiNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(poiCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poiDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poiIconField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poiCoordinateLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePOIButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(createPOIButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets the new POI's data. Refuses to edit the information if specific fields are missing.
     * @param evt Default Java event.
     */
    private void createPOIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPOIButtonActionPerformed
        // do checks and then edit/create the POI
        if (poiNameField.getText().equals("")) {
            errorLabel.setText("Name field cannot be blank");
            return;
        }
        
        if (poiCategoryField.getText().equals("")) {
            errorLabel.setText("Category field cannot be blank");
            return;
        }
        
        File iconpath = new File("data/icon/" + poiIconField.getText() + ".png");
        if (!iconpath.exists()) {
            errorLabel.setText(poiIconField.getText() + " is not a valid icon");
            return;
        }
        
        // good otherwise
        currentPOI.setName(poiNameField.getText());
        currentPOI.setDescription(poiDescriptionField.getText());
        currentPOI.setCategory(poiCategoryField.getText());

        // default icon instead
        if (poiIconField.getText().equals("")) currentPOI.setIcon("default");
        else currentPOI.setIcon(poiIconField.getText());

        this.dispose();
    }//GEN-LAST:event_createPOIButtonActionPerformed

    /**
     * Removes the POI by nullifying the content after a confirmation.
     * Cancels if we were inserting a new POI.
     * @param evt 
     */
    private void deletePOIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePOIButtonActionPerformed
        // poi not null
        if (currentPOI.getName() != null && currentPOI.getCategory() != null) {
            // confirm delete
            if (!confirmDelete) {
                confirmDelete = true;
                deletePOIButton.setText("Confirm?");
            }
            else {
                currentPOI.setName(null);
                currentPOI.setDescription(null);
                currentPOI.setIcon(null);
                
                this.dispose();
            }
        }
        // otherwise cancel
        else this.dispose();
    }//GEN-LAST:event_deletePOIButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POIEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POIEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POIEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POIEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Please run LoginForm instead");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPOIButton;
    private javax.swing.JButton deletePOIButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField poiCategoryField;
    private javax.swing.JLabel poiCoordinateLabel;
    private javax.swing.JTextField poiDescriptionField;
    private javax.swing.JTextField poiIconField;
    private javax.swing.JTextField poiNameField;
    // End of variables declaration//GEN-END:variables
}
